source 'https://rubygems.org'


gem 'rails', '5.0.0'
gem 'sqlite3'
gem "paperclip", "~> 5.0.0"
gem 'mechanize'

group :development, :test do
  gem 'pry'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

